version: "3.8"
services:
  web:
    build:
      context: .
      platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    volumes:
      - ./:/app:cached
    restart: unless-stopped
